import { chromium } from 'playwright';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/usr/local/bin/chromium',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.stack||e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const ok=(v,m)=>{if(!v)throw new Error(m)},today=new Date().toISOString().slice(0,10),availability={};for(let i=0;i<7;i++)availability[i]={enabled:true,start:'08:00',end:'22:00'};
const state={schemaVersion:7,areas:['個人','工作'],filter:'工作',tab:'today',todayMode:'focus',activeGoal:null,tlView:'week',scheduleDay:today,timelineExpanded:false,goalsView:'roadmap',settings:{todayLimit:10,reward:'garden',upcomingDays:7,reviewPopup:false,weekStart:'mon',availability,scheduling:{maxFocus:240,maxSession:120,breakMinutes:15}},goals:[{id:'g1',title:'出版作品集',area:'工作',kind:'achievement',color:'--blue',status:'active',focus:true,projects:[],tasks:[{id:'t1',title:'整理案例',due:today,estimate:60,estimateMinutes:60,done:false,target:1,count:0,pid:null,mid:null}],routines:[]}],events:[],sessions:[],timeBlocks:[],blockExceptions:[],externalEvents:[],dailyPlans:{[today]:{itemIds:['t1'],order:['t1']}},garden:{owned:[],placed:{},collection:[]},gardenTab:'garden',gardenNight:false,rewardTransactions:[],habitScheduleExceptions:[]};
await page.goto(process.env.GHT_URL||'http://127.0.0.1:4173');await page.evaluate(x=>{localStorage.clear();localStorage.setItem('ght_state_blank',JSON.stringify(x));},state);await page.reload();await page.waitForTimeout(100);
ok(await page.locator('#nav button').count()===3,'bottom nav is not three items');ok(await page.locator('#nav').getByText('花園').count()===0,'garden remains in bottom nav');
ok(await page.getByRole('button',{name:/開始本週規劃|本週規劃已設定/}).count()===1,'weekly planning entry missing on Today');
ok(await page.getByText('我的小島',{exact:false}).count()===1,'garden Hero missing');await page.getByText('我的小島',{exact:false}).click();ok(await page.evaluate(()=>state.tab)==='garden','garden Hero did not open garden');
await page.evaluate(()=>setTab('goals'));ok(await page.evaluate(()=>state.goalsView)==='list','Goals nav did not reset');ok(await page.getByRole('button',{name:'路線圖'}).count()===0,'Roadmap remains visible');ok(await page.getByText('顯示領域',{exact:true}).count()===0,'Area filter remains visible');
await page.evaluate(()=>openGoal('g1'));await page.locator('button.goalstatequiet').click();ok(await page.getByText('目標狀態',{exact:true}).count()===1,'status bottom sheet missing');await page.getByRole('button',{name:/暫停/}).click();ok(await page.evaluate(()=>state.goals[0].status)==='paused','status sheet did not update goal');await page.evaluate(()=>{state.goals[0].status='active';setTab('today')});
const grip=page.locator('.grip').first();if(await grip.count())ok(await grip.evaluate(el=>getComputedStyle(el).display)==='none','drag handle is still visible');
await page.locator('.fab').click();ok(await page.getByText('新增任務',{exact:true}).count()===1,'FAB did not open unified task editor');await page.locator('#afname').fill('晨間閱讀');await page.getByRole('checkbox').check();ok(await page.getByText('新增習慣',{exact:true}).count()===1,'habit switch did not open unified habit editor');await page.getByRole('button',{name:'建立習慣'}).click();ok(await page.evaluate(()=>state.goals[0].routines.some(x=>x.title==='晨間閱讀')),'habit switch did not create habit');
await page.locator('.fab').click();await page.locator('#afname').fill('挑選封面');await page.getByRole('button',{name:'建立任務'}).click();ok(await page.evaluate(()=>state.goals[0].tasks.some(x=>x.title==='挑選封面')),'FAB did not create task');
await page.getByRole('button',{name:/開始本週規劃|本週規劃已設定/}).click();ok(await page.getByText('每週規劃',{exact:true}).count()===1,'weekly planning flow did not open');await page.locator('.moretop button').click();ok(await page.evaluate(()=>state.tab)==='today','weekly planning back did not return Today');
await page.evaluate(()=>{state.tlView='week';setTab('timeline')});ok(await page.evaluate(()=>state.tlView)==='today','Schedule nav did not reset to Today');
await page.evaluate(()=>{state.tab='more';state.moreView=null;render()});ok(await page.getByRole('button',{name:/每週規劃/}).count()===0,'weekly planning remains duplicated in More');
await page.evaluate(()=>setTab('today'));const suggestion=page.getByText('整理案例',{exact:true}).first();if(await suggestion.count()){await suggestion.click();ok(await page.getByText('編輯任務',{exact:true}).count()===1,'suggested task title did not open unified editor');}
ok(errors.length===0,`browser errors: ${errors.join(' | ')}`);console.log('PASS: Phase 3.10C IA smoke');await browser.close();
